backend:
  name: git-gateway

media_folder: static/img
public_folder: img

collections:
  - name: "pages"
    label: "Sideopsætning"
    delete: false
    files:
      - file: "src/data/aabingstider.md"
        label: "Åbningstider"
        name: "aabingstider"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "aabningstider-component",
            }
          - {
              label: "Åbningstider",
              name: "aabningstider",
              widget: "list",
              fields:
                [
                  {
                    label: "Dag",
                    name: "day",
                    widget: "select",
                    default: "Mandag",
                    options:
                      ["Mandag", "Tirsdag", "Onsdag", "Torsdag", "Fredag"],
                  },
                  {
                    label: "Åben",
                    name: "open",
                    widget: "datetime",
                    default: "08:00",
                    format: "HH:mm",
                    dateFormat: false,
                    timeFormat: "H:mm",
                  },
                  {
                    label: "Luk",
                    name: "close",
                    widget: "datetime",
                    format: "HH:mm",
                    dateFormat: false,
                    timeFormat: "H:mm",
                    default: "12:10",
                  },
                ],
            }
          - {
              label: "Lørdage",
              name: "saturdays",
              widget: "list",
              field:
                {
                  Label: "Dato",
                  name: "date",
                  widget: "date",
                  format: "DD/MM/YYYY",
                  dateFormat: "DD/MM/YYYY",
                },
            }
      - file: "src/pages/index.md"
        label: "Hovedside"
        name: "index"
        delete: false
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Kasser",
              name: "boxes",
              widget: "list",
              fields:
                [
                  {
                    label: "Overskrift",
                    name: "title",
                    widget: "string",
                    required: true,
                  },
                  {
                    label: "Body",
                    name: "body",
                    widget: "text",
                    required: true,
                  },
                  {
                    label: "Link",
                    name: "link",
                    widget: "string",
                    required: true,
                  },
                  {
                    label: "Knap tekst",
                    name: "buttontext",
                    widget: "string",
                    default: "Læs mere!",
                    required: true,
                  },
                ],
            }
      - file: "src/pages/fysioterapeut/index.md"
        label: "Fysioterapeut"
        name: "fysioterapeut"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "fysioterapeut-page",
            }
          - {
              label: "Overskrift",
              name: "overskrift",
              widget: "string",
              required: true,
            }
          - { label: "Beskrivelse", name: "body", widget: "markdown" }
          - {
              label: "Specialer",
              name: "special",
              widget: "list",
              fields:
                [
                  { label: "Overskrift", name: "overskrift", widget: "string" },
                  { label: "Teaser", name: "teaser", widget: "text" },
                  { label: "Beskrivelse", name: "body", widget: "markdown" },
                ],
            }
      - file: "src/pages/zoneterapeut/index.md"
        label: "Zoneterapeut"
        name: "zoneterapeut"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "zoneterapeut-page",
            }
          - {
              label: "Overskrift",
              name: "overskrift",
              widget: "string",
              required: true,
            }
          - { label: "Beskrivelse", name: "body", widget: "markdown" }
          - {
              label: "Specialer",
              name: "special",
              widget: "list",
              fields:
                [
                  { label: "Overskrift", name: "overskrift", widget: "string" },
                  { label: "Teaser", name: "teaser", widget: "text" },
                  { label: "Beskrivelse", name: "body", widget: "markdown" },
                ],
            }
      - file: "src/pages/klinikken/index.md"
        label: "Klinikken"
        name: "klinikken"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "klinikken-page",
            }
          - {
              label: "Overskrift",
              name: "overskrift",
              widget: "string",
              required: true,
            }
          - { label: "Beskrivelse", name: "body", widget: "markdown" }
      - file: "src/pages/kiropraktor/index.md"
        label: "Kiropraktor"
        name: "kiropraktor"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "kiropraktor-page",
            }
          - {
              label: "Overskrift",
              name: "overskrift",
              widget: "string",
              required: true,
            }
          - { label: "Beskrivelse", name: "body", widget: "markdown" }
          - {
              label: "Specialer",
              name: "special",
              widget: "list",
              fields:
                [
                  { label: "Overskrift", name: "overskrift", widget: "string" },
                  { label: "Teaser", name: "teaser", widget: "text" },
                  { label: "Beskrivelse", name: "body", widget: "markdown" },
                ],
            }
      - file: "src/pages/massage/index.md"
        label: "Massør"
        name: "massage"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "massage-page",
            }
          - {
              label: "Overskrift",
              name: "overskrift",
              widget: "string",
              required: true,
            }
          - { label: "Beskrivelse", name: "body", widget: "markdown" }
          - {
              label: "Specialer",
              name: "special",
              widget: "list",
              fields:
                [
                  { label: "Overskrift", name: "overskrift", widget: "string" },
                  { label: "Teaser", name: "teaser", widget: "text" },
                  { label: "Beskrivelse", name: "body", widget: "markdown" },
                ],
            }
      - file: "src/pages/klinikken/index.md"
        label: "Klinikken"
        name: "klinikken"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "klinikken-page",
            }
          - { label: "Title", name: "title", widget: "string" }
  - label: "Ansatte"
    name: "ansatte"
    folder: "src/data/ansatte"
    create: true
    identifier_field: name
    fields:
      - { label: "Navn", name: "name", widget: "string", required: true }
      - { label: "Foto", name: "img", widget: "image", required: true }
      - { label: "Beskrivelse", name: "description", widget: "text" }
      - {
          label: "Kategori",
          name: "type",
          widget: "select",
          options: ["Kiropraktor", "Massør", "Fysioterapeut"],
        }
  - label: "Gode Råd"
    name: "goderaad"
    folder: "src/data/raad"
    create: true
    identifier_field: overskrift
    fields:
      - { label: "Overskrift", name: "overskrift", widget: "string" }
      - { label: "Råd", name: "raad", widget: "text" }
